import { DefaultTheme, configureFonts } from 'react-native-paper';

const fontConfig = {
  default: {
    displayLarge: {
      fontFamily: 'Roboto-Bold',
      fontWeight: '700' as const,
      fontSize: 57,
      letterSpacing: -0.25,
      lineHeight: 64,
    },
    displayMedium: {
      fontFamily: 'Roboto-Bold',
      fontWeight: '700' as const,
      fontSize: 45,
      letterSpacing: 0,
      lineHeight: 52,
    },
    displaySmall: {
      fontFamily: 'Roboto-Bold',
      fontWeight: '700' as const,
      fontSize: 36,
      letterSpacing: 0,
      lineHeight: 44,
    },
    headlineLarge: {
      fontFamily: 'Roboto-Medium',
      fontWeight: '500' as const,
      fontSize: 32,
      letterSpacing: 0,
      lineHeight: 40,
    },
    headlineMedium: {
      fontFamily: 'Roboto-Medium',
      fontWeight: '500' as const,
      fontSize: 28,
      letterSpacing: 0,
      lineHeight: 36,
    },
    headlineSmall: {
      fontFamily: 'Roboto-Medium',
      fontWeight: '500' as const,
      fontSize: 24,
      letterSpacing: 0,
      lineHeight: 32,
    },
    titleLarge: {
      fontFamily: 'Roboto-Medium',
      fontWeight: '500' as const,
      fontSize: 22,
      letterSpacing: 0,
      lineHeight: 28,
      color: '#000000',
    },
    titleMedium: {
      fontFamily: 'Roboto-Medium',
      fontWeight: '500' as const,
      fontSize: 16,
      letterSpacing: 0.15,
      lineHeight: 24,
    },
    titleSmall: {
      fontFamily: 'Roboto-Medium',
      fontWeight: '500' as const,
      fontSize: 14,
      letterSpacing: 0.1,
      lineHeight: 20,
    },
    bodyLarge: {
      fontFamily: 'Roboto-Regular',
      fontWeight: '400' as const,
      fontSize: 16,
      letterSpacing: 0.5,
      lineHeight: 24,
    },
    bodyMedium: {
      fontFamily: 'Roboto-Regular',
      fontWeight: '400' as const,
      fontSize: 14,
      letterSpacing: 0.25,
      lineHeight: 20,
    },
    bodySmall: {
      fontFamily: 'Roboto-Regular',
      fontWeight: '400' as const,
      fontSize: 12,
      letterSpacing: 0.4,
      lineHeight: 16,
    },
    labelLarge: {
      fontFamily: 'Roboto-Medium',
      fontWeight: '500' as const,
      fontSize: 14,
      letterSpacing: 0.1,
      lineHeight: 20,
    },
    labelMedium: {
      fontFamily: 'Roboto-Medium',
      fontWeight: '500' as const,
      fontSize: 12,
      letterSpacing: 0.5,
      lineHeight: 16,
    },
    labelSmall: {
      fontFamily: 'Roboto-Medium',
      fontWeight: '500' as const,
      fontSize: 11,
      letterSpacing: 0.5,
      lineHeight: 16,
    },
  },
};

export const theme = {
  ...DefaultTheme,
  fonts: configureFonts({ config: fontConfig.default, isV3: true }),
  colors: {
    ...DefaultTheme.colors,
    primary: '#02302e',
    accent: '#edefef',
    secondaryContainer: '#F0F0F0',
    secondary: '#757575',
    background: '#FFFFFF',
    surface: '#F0F0F0',
    onSurface: '#757575',
    error: '#B00020',
    onPrimary: '#FFFFFF',
    onSecondary: '#000000',
    onBackground: '#000000',
    onError: '#FFFFFF',
  },
  roundness: 8,
  animation: {
    scale: 1.0,
  },
};
